const ALL = ["kongs", "home", "hotel", "bodyweight"];

const exercise = (id, name, locations, patterns, prescription, options = {}) => ({
  id,
  name,
  locations,
  patterns,
  prescription,
  equipment: [],
  family: id,
  role: "primary",
  stable: false,
  demand: "medium",
  conflicts: [],
  cue: "",
  ...options,
});

const kongs = (id, name, patterns, prescription, options) => exercise(id, name, ["kongs"], patterns, prescription, options);
const home = (id, name, patterns, prescription, options) => exercise(id, name, ["home"], patterns, prescription, options);
const hotel = (id, name, equipment, patterns, prescription, options = {}) => exercise(id, name, ["hotel"], patterns, prescription, { ...options, equipment });
const body = (id, name, patterns, prescription, options = {}) => exercise(id, name, ALL, patterns, prescription, options);
const kb = (id, name, patterns, prescription, options = {}) => exercise(id, name, ["home", "kongs"], patterns, prescription, options);
const mobility = (id, name, patterns, prescription, options = {}) => exercise(id, name, ALL, patterns, prescription, { role: "mobility", stable: true, ...options });

export const EXERCISES = [
  // Kongs — pressing uses dumbbells, machines and cables; no barbell pressing.
  kongs("k-dip", "Chest dip", ["chest", "triceps"], "2 x 6–12", { family: "chest-dip", demand: "high", conflicts: ["shoulder", "elbow", "wrist"] }),
  kongs("k-incline-db", "Incline dumbbell bench press", ["chest"], "2 x 6–12", { family: "chest-incline", demand: "high", conflicts: ["shoulder", "elbow"], cue: "Use a comfortable semi-neutral grip." }),
  kongs("k-iso-chest", "Iso-lateral chest press", ["chest"], "2 x 6–12", { family: "chest-flat", stable: true }),
  kongs("k-incline-machine", "Incline chest press machine", ["chest"], "2 x 8–12", { family: "chest-incline", stable: true }),
  kongs("k-cable-chest", "Cable chest press", ["chest"], "2 x 10–15", { family: "chest-flat", stable: true }),
  kongs("k-iso-shoulder", "Iso-lateral shoulder press", ["shoulderPress"], "2 x 6–12", { family: "shoulder-machine", stable: true, conflicts: ["shoulder"] }),
  kongs("k-db-shoulder", "Neutral-grip dumbbell shoulder press", ["shoulderPress"], "2 x 6–12", { family: "shoulder-db", demand: "high", conflicts: ["shoulder", "elbow"] }),
  kongs("k-plate-shoulder", "Plate-loaded shoulder press", ["shoulderPress"], "2 x 8–12", { family: "shoulder-machine", stable: true, conflicts: ["shoulder"] }),
  kongs("k-pushdown", "Rope triceps pushdown", ["triceps"], "2 x 10–20", { family: "triceps-cable", role: "accessory", stable: true, conflicts: ["elbow"] }),
  kongs("k-crossbody-triceps", "Cross-body cable triceps extension", ["triceps"], "2 x 12–20", { family: "triceps-cable", role: "accessory", stable: true, conflicts: ["elbow"] }),
  kongs("k-cable-lateral", "Cable lateral raise", ["lateralDelt"], "2 x 12–20", { family: "lateral-cable", role: "accessory", stable: true, conflicts: ["shoulder"] }),
  kongs("k-lateral-machine", "Lateral raise machine", ["lateralDelt"], "2 x 12–20", { family: "lateral-machine", role: "accessory", stable: true, conflicts: ["shoulder"] }),

  kongs("k-neutral-pulldown", "Neutral-grip lat pulldown", ["verticalPull"], "2 x 6–12", { family: "vertical-neutral", stable: true, conflicts: ["shoulder", "elbow"] }),
  kongs("k-iso-pulldown", "Neutral-grip iso-lateral pulldown", ["verticalPull"], "2 x 8–12", { family: "vertical-iso", stable: true, conflicts: ["shoulder", "elbow"] }),
  kongs("k-pullup", "Neutral-grip pull-up", ["verticalPull"], "2 x 6–12", { family: "vertical-pullup", demand: "high", conflicts: ["shoulder", "elbow"] }),
  kongs("k-high-row", "Iso-lateral high row", ["horizontalPull"], "2 x 6–12", { family: "row-iso", stable: true }),
  kongs("k-cable-row", "Neutral-grip seated cable row", ["horizontalPull"], "2 x 6–12", { family: "row-cable", stable: true }),
  kongs("k-single-cable-row", "Single-arm cable row", ["horizontalPull"], "2 x 8–12 each side", { family: "row-single", stable: true }),
  kongs("k-face-pull", "Cable face pull", ["rearDelt"], "2 x 12–20", { family: "rear-face-pull", role: "accessory", stable: true }),
  kongs("k-rear-fly", "Cable rear-delt fly", ["rearDelt"], "2 x 12–20", { family: "rear-fly", role: "accessory", stable: true }),
  kongs("k-hammer-curl", "Dumbbell hammer curl", ["biceps"], "2 x 8–15", { family: "curl-hammer", role: "accessory", conflicts: ["elbow"] }),
  kongs("k-rope-curl", "Rope cable curl", ["biceps"], "2 x 10–20", { family: "curl-cable", role: "accessory", stable: true, conflicts: ["elbow"] }),
  kongs("k-single-cable-curl", "Single-arm cable curl", ["biceps"], "2 x 10–20", { family: "curl-single", role: "accessory", stable: true, conflicts: ["elbow"] }),

  kongs("k-hack", "Hack squat", ["squat", "quad"], "2 x 10–20", { family: "squat-hack", stable: true, demand: "high", conflicts: ["hip", "knee", "back"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kongs("k-leg-press", "Leg press", ["squat", "quad"], "2 x 10–20", { family: "squat-leg-press", stable: true, conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kongs("k-iso-leg-press", "Iso-lateral leg press", ["squat", "quad"], "2 x 10–20", { family: "squat-iso-press", stable: true, conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kongs("k-bulgarian", "Barbell Bulgarian split squat", ["unilateral", "quad"], "2 x 10–20 each side", { family: "lunge-bulgarian", demand: "high", conflicts: ["hip", "knee", "back"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kongs("k-reverse-lunge", "Supported reverse lunge", ["unilateral", "quad"], "2 x 10–20 each side", { family: "lunge-reverse", stable: true, conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kongs("k-leg-extension", "Leg extension", ["quadIsolation"], "2 x 12–20", { family: "quad-extension", role: "accessory", stable: true, conflicts: ["knee"] }),
  kongs("k-ham-curl", "Seated hamstring curl", ["hamstring"], "2 x 10–20", { family: "ham-curl-seated", stable: true }),
  kongs("k-iso-ham", "Iso-lateral hamstring curl", ["hamstring"], "2 x 10–20", { family: "ham-curl-iso", stable: true }),
  kongs("k-rdl-machine", "RDL machine", ["hamstring", "hinge"], "2 x 10–15", { family: "ham-rdl-machine", stable: true, conflicts: ["hip", "back"], cue: "Start light while learning the machine path." }),
  kongs("k-glute-machine", "Glute drive machine", ["hamstring", "glute"], "2 x 10–20", { family: "glute-machine", stable: true, conflicts: ["hip", "back"] }),
  kongs("k-calf", "Standing calf raise machine", ["calves"], "2 x 12–20", { family: "calves", role: "accessory", stable: true }),
  kongs("k-adductor", "Hip adductor machine", ["adductors"], "2 x 12–20", { family: "adductors", role: "accessory", stable: true, conflicts: ["hip"] }),
  kongs("k-abductor", "Hip abductor machine", ["abductors"], "2 x 12–20", { family: "abductors", role: "accessory", stable: true, conflicts: ["hip"] }),

  // Home / garage — known kettlebells, rings, bands, parallettes and pull-up bar.
  home("h-ring-pushup", "Ring push-up", ["chest"], "2 x 8–15", { family: "chest-ring", conflicts: ["shoulder", "wrist"] }),
  home("h-kb-floor", "Double-kettlebell floor press", ["chest"], "2 x 6–12", { family: "chest-floor", conflicts: ["shoulder", "elbow", "wrist"], cue: "Use a neutral grip." }),
  home("h-parallette-pushup", "Parallette push-up", ["chest"], "2 x 8–20", { family: "chest-parallette", conflicts: ["shoulder"] }),
  home("h-kb-press", "Double-kettlebell press", ["shoulderPress"], "2 x 6–12", { family: "shoulder-kb", demand: "high", conflicts: ["shoulder", "elbow", "wrist"] }),
  home("h-single-kb-press", "Half-kneeling single-kettlebell press", ["shoulderPress"], "2 x 8–12 each side", { family: "shoulder-half-kneeling", conflicts: ["shoulder", "hip"] }),
  home("h-band-triceps", "Band triceps pressdown", ["triceps"], "2 x 12–20", { family: "triceps-band", role: "accessory", stable: true, conflicts: ["elbow"] }),
  home("h-band-lateral", "Band lateral raise", ["lateralDelt"], "2 x 12–20", { family: "lateral-band", role: "accessory", conflicts: ["shoulder"] }),
  home("h-pullup", "Neutral-grip pull-up", ["verticalPull"], "2 x 6–12", { family: "vertical-pullup", demand: "high", conflicts: ["shoulder", "elbow"] }),
  home("h-band-pulldown", "Neutral-grip band pulldown", ["verticalPull"], "2 x 12–20", { family: "vertical-band", stable: true, conflicts: ["shoulder", "elbow"] }),
  home("h-ring-row", "Ring row", ["horizontalPull"], "2 x 8–15", { family: "row-ring" }),
  home("h-kb-row", "Supported single-kettlebell row", ["horizontalPull"], "2 x 8–12 each side", { family: "row-kb", stable: true }),
  home("h-band-face", "Band face pull", ["rearDelt"], "2 x 12–20", { family: "rear-face-pull", role: "accessory", stable: true }),
  home("h-kb-hammer", "Kettlebell hammer curl", ["biceps"], "2 x 8–15", { family: "curl-hammer", role: "accessory", conflicts: ["elbow"] }),
  home("h-band-curl", "Neutral-grip band curl", ["biceps"], "2 x 12–20", { family: "curl-band", role: "accessory", stable: true, conflicts: ["elbow"] }),
  home("h-goblet", "Kettlebell goblet squat", ["squat", "quad"], "2 x 10–20", { family: "squat-goblet", conflicts: ["hip", "knee", "back"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  home("h-split", "Kettlebell split squat", ["unilateral", "quad"], "2 x 10–20 each side", { family: "lunge-split", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  home("h-kb-rdl", "Double-kettlebell Romanian deadlift", ["hamstring", "hinge"], "2 x 10–15", { family: "ham-rdl", demand: "high", conflicts: ["hip", "back"] }),
  home("h-ham-walkout", "Hamstring walkout", ["hamstring"], "2 x 10–15", { family: "ham-walkout" }),
  home("h-calf", "Single-leg calf raise", ["calves"], "2 x 12–20 each side", { family: "calves", role: "accessory" }),
  home("h-side-lunge", "Bodyweight side lunge", ["adductors"], "2 x 10–15 each side", { family: "adductors", role: "accessory", conflicts: ["hip", "knee"] }),
  home("h-band-abduction", "Band hip abduction", ["abductors"], "2 x 15–20", { family: "abductors", role: "accessory", stable: true, conflicts: ["hip"] }),

  // Hotel equipment is explicit. Exercises with no requirement remain bodyweight.
  hotel("t-db-floor", "Neutral-grip dumbbell floor press", ["dumbbells"], ["chest"], "2 x 8–12", { family: "chest-floor", conflicts: ["shoulder", "elbow"] }),
  hotel("t-db-bench", "Neutral-grip dumbbell bench press", ["dumbbells", "bench"], ["chest"], "2 x 6–12", { family: "chest-flat", conflicts: ["shoulder", "elbow"] }),
  hotel("t-cable-chest", "Cable chest press", ["cable"], ["chest"], "2 x 10–15", { family: "chest-flat", stable: true }),
  hotel("t-db-press", "Neutral-grip dumbbell shoulder press", ["dumbbells"], ["shoulderPress"], "2 x 8–12", { family: "shoulder-db", conflicts: ["shoulder", "elbow"] }),
  hotel("t-cable-press", "Single-arm cable shoulder press", ["cable"], ["shoulderPress"], "2 x 10–15 each side", { family: "shoulder-cable", stable: true, conflicts: ["shoulder"] }),
  hotel("t-pushdown", "Rope triceps pushdown", ["cable"], ["triceps"], "2 x 12–20", { family: "triceps-cable", role: "accessory", stable: true }),
  hotel("t-lateral", "Cable lateral raise", ["cable"], ["lateralDelt"], "2 x 12–20", { family: "lateral-cable", role: "accessory", stable: true }),
  hotel("t-pulldown", "Neutral-grip lat pulldown", ["cable"], ["verticalPull"], "2 x 8–12", { family: "vertical-neutral", stable: true, conflicts: ["shoulder", "elbow"] }),
  hotel("t-pullup", "Neutral-grip pull-up", ["pullup"], ["verticalPull"], "2 x 6–12", { family: "vertical-pullup", demand: "high", conflicts: ["shoulder", "elbow"] }),
  hotel("t-cable-row", "Neutral-grip cable row", ["cable"], ["horizontalPull"], "2 x 8–12", { family: "row-cable", stable: true }),
  hotel("t-db-row", "Supported dumbbell row", ["dumbbells", "bench"], ["horizontalPull"], "2 x 8–12 each side", { family: "row-db", stable: true }),
  hotel("t-face-pull", "Cable face pull", ["cable"], ["rearDelt"], "2 x 12–20", { family: "rear-face-pull", role: "accessory", stable: true }),
  hotel("t-hammer", "Dumbbell hammer curl", ["dumbbells"], ["biceps"], "2 x 8–15", { family: "curl-hammer", role: "accessory", conflicts: ["elbow"] }),
  hotel("t-rope-curl", "Rope cable curl", ["cable"], ["biceps"], "2 x 12–20", { family: "curl-cable", role: "accessory", stable: true }),
  hotel("t-goblet", "Dumbbell goblet squat", ["dumbbells"], ["squat", "quad"], "2 x 10–20", { family: "squat-goblet", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  hotel("t-leg-press", "Leg press machine", ["machines"], ["squat", "quad"], "2 x 10–20", { family: "squat-leg-press", stable: true, conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  hotel("t-split", "Dumbbell split squat", ["dumbbells"], ["unilateral", "quad"], "2 x 10–20 each side", { family: "lunge-split", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  hotel("t-leg-extension", "Leg extension machine", ["machines"], ["quadIsolation"], "2 x 12–20", { family: "quad-extension", role: "accessory", stable: true }),
  hotel("t-leg-curl", "Leg curl machine", ["machines"], ["hamstring"], "2 x 10–20", { family: "ham-curl", stable: true }),
  hotel("t-db-rdl", "Dumbbell Romanian deadlift", ["dumbbells"], ["hamstring", "hinge"], "2 x 10–15", { family: "ham-rdl", conflicts: ["hip", "back"] }),
  hotel("t-calf", "Standing calf raise", [], ["calves"], "2 x 15–20", { family: "calves", role: "accessory" }),

  // Bodyweight — deliberately no improvised pulling without known equipment.
  body("b-pushup", "Push-up", ["chest"], "2 x 10–20", { family: "chest-pushup", conflicts: ["shoulder", "wrist"] }),
  body("b-close-pushup", "Close-grip push-up", ["triceps"], "2 x 10–20", { family: "triceps-pushup", role: "accessory", conflicts: ["shoulder", "elbow", "wrist"] }),
  body("b-pike", "Pike push-up", ["shoulderPress"], "2 x 8–15", { family: "shoulder-pike", conflicts: ["shoulder", "wrist"] }),
  body("b-squat", "Bodyweight squat", ["squat", "quad"], "2 x 15–20", { family: "squat-bodyweight", cue: "Use a comfortable unweighted range." }),
  body("b-reverse-lunge", "Bodyweight reverse lunge", ["unilateral", "quad"], "2 x 10–20 each side", { family: "lunge-reverse", conflicts: ["hip", "knee"], cue: "Use a comfortable unweighted range." }),
  body("b-sissy", "Supported sissy squat", ["quadIsolation"], "2 x 10–20", { family: "quad-sissy", role: "accessory", conflicts: ["knee"] }),
  body("b-ham-walk", "Hamstring walkout", ["hamstring"], "2 x 10–15", { family: "ham-walkout", conflicts: ["back"] }),
  body("b-bridge", "Single-leg glute bridge", ["hamstring", "glute"], "2 x 10–20 each side", { family: "glute-bridge", conflicts: ["hip", "back"] }),
  body("b-calf", "Single-leg calf raise", ["calves"], "2 x 15–20 each side", { family: "calves", role: "accessory" }),
  body("b-side-lunge", "Bodyweight side lunge", ["adductors"], "2 x 10–15 each side", { family: "adductors", role: "accessory", conflicts: ["hip", "knee"] }),
  body("b-side-leg", "Side-lying leg raise", ["abductors"], "2 x 15–20 each side", { family: "abductors", role: "accessory", stable: true, conflicts: ["hip"] }),
  body("b-dead-bug", "Dead bug", ["core"], "2 x 8–12 each side", { family: "core-dead-bug", role: "accessory", stable: true }),
  body("b-side-plank", "Side plank", ["core"], "2 x 25–40 sec each side", { family: "core-side-plank", role: "accessory", conflicts: ["shoulder"] }),

  // Kettlebell athletic menu. Home is the default; hotel needs kettlebells.
  kb("kb-swing", "Two-hand kettlebell swing", ["kbPower", "hinge"], "2 x 15–20", { family: "kb-swing", demand: "high", conflicts: ["hip", "back"] }),
  kb("kb-clean-squat-press", "Clean, squat & press complex", ["kbComplex", "kbPower", "squat", "shoulderPress"], "2 rounds · 3+3+3 reps", { family: "kb-complex-csp", demand: "high", conflicts: ["shoulder", "hip", "back", "knee"] }),
  kb("kb-swing-row-complex", "Swing & row complex", ["kbComplex", "kbPower", "horizontalPull"], "2 rounds · 10 swings + 6 rows", { family: "kb-complex-row", demand: "high", conflicts: ["hip", "back"] }),
  kb("kb-goblet", "Kettlebell goblet squat", ["squat", "quad"], "2 x 10–20", { family: "squat-goblet", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kb("kb-reverse-lunge", "Front-rack kettlebell reverse lunge", ["unilateral", "quad"], "2 x 10–15 each side", { family: "lunge-kb", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  kb("kb-push-press", "Single-kettlebell push press", ["shoulderPress"], "2 x 6–10 each side", { family: "shoulder-kb-push", demand: "high", conflicts: ["shoulder", "elbow"] }),
  kb("kb-floor", "Kettlebell floor press", ["chest"], "2 x 8–12 each side", { family: "chest-floor", conflicts: ["shoulder", "elbow"] }),
  kb("kb-row", "Supported kettlebell row", ["horizontalPull"], "2 x 8–12 each side", { family: "row-kb", stable: true }),
  kb("kb-dead-bug", "Kettlebell dead bug pullover", ["core"], "2 x 8–12", { family: "core-kb", role: "accessory", stable: true, conflicts: ["shoulder"] }),
  hotel("tkb-swing", "Two-hand kettlebell swing", ["kettlebells"], ["kbPower", "hinge"], "2 x 15–20", { family: "kb-swing", demand: "high", conflicts: ["hip", "back"] }),
  hotel("tkb-complex", "Clean, squat & press complex", ["kettlebells"], ["kbComplex", "kbPower", "squat", "shoulderPress"], "2 rounds · 3+3+3 reps", { family: "kb-complex-csp", demand: "high", conflicts: ["shoulder", "hip", "back", "knee"] }),
  hotel("tkb-goblet", "Kettlebell goblet squat", ["kettlebells"], ["squat", "quad"], "2 x 10–20", { family: "squat-goblet", conflicts: ["hip", "knee"], cue: "Loaded depth: stop at the clinician-advised 45° limit." }),
  hotel("tkb-row", "Supported kettlebell row", ["kettlebells"], ["horizontalPull"], "2 x 8–12 each side", { family: "row-kb", stable: true }),
  hotel("tkb-floor", "Kettlebell floor press", ["kettlebells"], ["chest"], "2 x 8–12 each side", { family: "chest-floor", conflicts: ["shoulder", "elbow"] }),

  // Mobility is intentionally consistent and low-variation.
  mobility("m-cat-cow", "Cat-cow with pelvic tilt", ["mobilitySpine"], "2 x 6–8 slow reps", { family: "mobility-spine" }),
  mobility("m-open-book", "Open-book rotation", ["mobilitySpine"], "2 x 6 each side", { family: "mobility-rotation" }),
  mobility("m-wall-slide", "Wall slide", ["mobilityShoulder"], "2 x 8–12", { family: "mobility-shoulder", conflicts: ["shoulder"] }),
  mobility("m-hip-rock", "Supported hip-flexor rock", ["mobilityHip"], "2 x 8 each side", { family: "mobility-hip", conflicts: ["hip", "knee"], cue: "Stay in an easy, symptom-free range." }),
  mobility("m-ankle-rock", "Supported ankle rock", ["mobilityAnkle"], "2 x 10 each side", { family: "mobility-ankle", conflicts: ["ankle"] }),
  mobility("m-bird-dog", "Bird dog", ["mobilityCore"], "2 x 6 each side", { family: "mobility-core", conflicts: ["wrist"] }),
  mobility("m-breath", "Crocodile breathing", ["breathing"], "3–5 min", { family: "breathing" }),
  mobility("m-walk", "Easy walk", ["walking"], "8–12 min", { family: "walking", conflicts: ["ankle", "knee"] }),
];

export const EXERCISE_BY_ID = new Map(EXERCISES.map((item) => [item.id, item]));
